<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Query\QueryBuilder;
use Doctrine\ORM\EntityManager;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository
{
    private $em;

    public function __construct(EntityManager $em)
    {
        $this->em = $em;
    }

    public function findAllQuery() : QueryBuilder
    {
        $queryBuilder = new QueryBuilder($this->em->getConnection());

        $queryBuilder->select('b.id, b.title, b.text, b.date');
        $queryBuilder->from('blog', 'b');
        $queryBuilder->orderBy('b.date', 'DESC');

        return $queryBuilder;
    }

    public function findById(int $id)
    {
        $queryBuilder = new QueryBuilder($this->em->getConnection());

        $queryBuilder->select('b.title, b.text, b.date');
        $queryBuilder->from('blog', 'b');
        $queryBuilder->where('id = :id');

        $queryBuilder->setParameters(array('id' => $id));

        return $queryBuilder->execute()->fetch();
    }
}
