<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Query\QueryBuilder;
use Doctrine\ORM\EntityManager;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository
{
    private $em;

    public function __construct(EntityManager $em)
    {
        $this->em = $em;
    }

    public function findByUsername($username)
    {
        $queryBuilder = new QueryBuilder($this->em->getConnection());

        $queryBuilder->select('u.username, u.password, u.name');
        $queryBuilder->from('users', 'u');
        $queryBuilder->where('u.username = :username');
        $queryBuilder->setParameters(array('username' => $username));

        return $queryBuilder->execute()->fetch();
    }

}
