# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
          algorithm: md5
          encode_as_base64: false
          iterations: 0

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            id: security.user.provider
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: user_provider
            form_login:
                username_parameter:       username
                password_parameter:       password
                check_path:               api_user_security_login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        refresh:
            pattern:  ^/api/token
            stateless: true
            anonymous: true

        # DOC
        doc_login:
            pattern: ^/api/doc
            provider: user_provider
            http_basic: ~
            anonymous: ~

        api:
            pattern:   ^/api
            stateless: true
            provider: user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

    access_control:
      - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/doc,       roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/, role: IS_AUTHENTICATED_FULLY }